/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sinninglopezcamilojose;

import Lists.ListDonations;
import Lists.ListStreamers;
import Lists.ListViewers;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Scanner;
import static sinninglopezcamilojose.SinningLopezCamiloJose.ad;
import static sinninglopezcamilojose.SinningLopezCamiloJose.as;
import static sinninglopezcamilojose.SinningLopezCamiloJose.av;
import static sinninglopezcamilojose.SinningLopezCamiloJose.myViewers;
import static sinninglopezcamilojose.SinningLopezCamiloJose.myStreamers;
import static sinninglopezcamilojose.SinningLopezCamiloJose.myDonations;
import static sinninglopezcamilojose.SinningLopezCamiloJose.myStreamers;
import static sinninglopezcamilojose.SinningLopezCamiloJose.myViewers;

/**
 *
 * @author camil
 */
public class FE extends javax.swing.JFrame {

    /**
     * Creates new form FE
     */
    public FE() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GUI = new javax.swing.JFrame();
        searchTextField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        idAddTextField = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        stringAddTextField = new javax.swing.JTextField();
        floatAddTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        generateButton = new javax.swing.JButton();
        sortComboBox = new javax.swing.JComboBox<>();
        sortButton = new javax.swing.JButton();
        calcComboBox = new javax.swing.JComboBox<>();
        calcButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        addComboBox = new javax.swing.JComboBox<>();
        showComboBox = new javax.swing.JComboBox<>();
        showButton = new javax.swing.JButton();
        searchComboBox = new javax.swing.JComboBox<>();
        saveButton = new javax.swing.JButton();
        consoleButton = new javax.swing.JButton();
        GUIButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        GUI.setMinimumSize(new java.awt.Dimension(610, 310));
        GUI.setPreferredSize(new java.awt.Dimension(610, 310));
        GUI.setSize(new java.awt.Dimension(610, 310));

        searchButton.setText("Search");
        searchButton.setEnabled(false);
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        addButton.setText("Add");
        addButton.setEnabled(false);
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        floatAddTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floatAddTextFieldActionPerformed(evt);
            }
        });

        textArea.setColumns(20);
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        generateButton.setText("Generate");
        generateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateButtonActionPerformed(evt);
            }
        });

        sortComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Donations", "Streamers", "Viewers" }));

        sortButton.setText("Sort");
        sortButton.setEnabled(false);
        sortButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortButtonActionPerformed(evt);
            }
        });

        calcComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Donations", "Streamers", "Viewers" }));

        calcButton.setText("Calc");
        calcButton.setEnabled(false);
        calcButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("id");

        jLabel3.setText("id");

        jLabel4.setText("string");

        jLabel5.setText("float");

        addComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Donation", "Streamer", "Viewer" }));

        showComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Donations", "Streamers", "Viewers" }));

        showButton.setText("show");
        showButton.setEnabled(false);
        showButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showButtonActionPerformed(evt);
            }
        });

        searchComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Donation", "Streamer", "Viewer" }));

        saveButton.setText("save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout GUILayout = new javax.swing.GroupLayout(GUI.getContentPane());
        GUI.getContentPane().setLayout(GUILayout);
        GUILayout.setHorizontalGroup(
            GUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GUILayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(GUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GUILayout.createSequentialGroup()
                        .addGroup(GUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(GUILayout.createSequentialGroup()
                                .addGroup(GUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(GUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(GUILayout.createSequentialGroup()
                                        .addGroup(GUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(stringAddTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                                            .addComponent(idAddTextField)
                                            .addComponent(floatAddTextField))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(GUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                                            .addComponent(addComboBox, 0, 0, Short.MAX_VALUE)))
                                    .addGroup(GUILayout.createSequentialGroup()
                                        .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(GUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(searchButton, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                                            .addComponent(searchComboBox, 0, 0, Short.MAX_VALUE)))))
                            .addGroup(GUILayout.createSequentialGroup()
                                .addComponent(saveButton)
                                .addGap(90, 90, 90)))
                        .addGap(18, 30, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(generateButton)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GUILayout.createSequentialGroup()
                        .addGroup(GUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(calcComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sortComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(showComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(GUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sortButton)
                            .addComponent(calcButton)
                            .addComponent(showButton))
                        .addGap(134, 134, 134))))
        );
        GUILayout.setVerticalGroup(
            GUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GUILayout.createSequentialGroup()
                .addGroup(GUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(GUILayout.createSequentialGroup()
                            .addGroup(GUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(GUILayout.createSequentialGroup()
                                    .addGap(27, 27, 27)
                                    .addGroup(GUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2)))
                                .addGroup(GUILayout.createSequentialGroup()
                                    .addGap(14, 14, 14)
                                    .addComponent(searchButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(searchComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(GUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(GUILayout.createSequentialGroup()
                                    .addGap(27, 27, 27)
                                    .addGroup(GUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(idAddTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(GUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(stringAddTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(GUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(floatAddTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5)))
                                .addGroup(GUILayout.createSequentialGroup()
                                    .addGap(41, 41, 41)
                                    .addComponent(addButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(addComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(GUILayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(generateButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(GUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sortComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sortButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(GUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calcComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calcButton)
                    .addComponent(saveButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(GUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showButton))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        consoleButton.setText("Console");
        consoleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consoleButtonActionPerformed(evt);
            }
        });

        GUIButton.setText("GUI");
        GUIButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GUIButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Mode:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(consoleButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addComponent(GUIButton)
                .addGap(76, 76, 76))
            .addGroup(layout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GUIButton)
                    .addComponent(consoleButton))
                .addGap(66, 66, 66))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consoleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consoleButtonActionPerformed
        setVisible(false);
    }//GEN-LAST:event_consoleButtonActionPerformed

    private void GUIButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GUIButtonActionPerformed
        setVisible(false);
        GUI.setVisible(true);
    }//GEN-LAST:event_GUIButtonActionPerformed

    private void floatAddTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floatAddTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_floatAddTextFieldActionPerformed

    private void generateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateButtonActionPerformed
        myDonations = ad.read();
        myStreamers = as.read();
        myViewers = av.read();
        searchButton.setEnabled(true);
        sortButton.setEnabled(true);
        addButton.setEnabled(true);
        calcButton.setEnabled(true);
        showButton.setEnabled(true);
    }//GEN-LAST:event_generateButtonActionPerformed

    private void showButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showButtonActionPerformed
        if (showComboBox.getSelectedIndex() == 0) {
            textArea.setText("The donation list is: ");
            textArea.append("\n--------------------------");
            ListDonations p = new ListDonations();
            p = myDonations;
            while ((p != null) && (p.myDonation != null)) {
                textArea.append("\nDonation: " + p.myDonation.idDonations);
                textArea.append("\nMessage: " + p.myDonation.msg);
                textArea.append("\nMoney: " + p.myDonation.money);
                textArea.append("\n---------------------------");
                p = p.link;
            }
        }
        if (showComboBox.getSelectedIndex() == 1) {
            textArea.setText("The Streamers list is: ");
            textArea.append("\n--------------------------");
            ListStreamers p = new ListStreamers();
            p = myStreamers;
            while ((p != null) && (p.myStreamer != null)) {
                textArea.append("\nStreamer: " + p.myStreamer.idStreamer);
                textArea.append("\nUsername: " + p.myStreamer.userName);
                textArea.append("\nFollowers: " + p.myStreamer.followers);
                textArea.append("\n---------------------------");
                p = p.link;
            }
        }
        if (showComboBox.getSelectedIndex() == 2) {
            textArea.setText("The viewers list is: ");
            textArea.append("\n--------------------------");
            ListViewers p = new ListViewers();
            p = myViewers;
            while ((p != null) && (p.myViewer != null)) {
                textArea.append("\nViewer: " + p.myViewer.idViewer);
                textArea.append("\nUsername: " + p.myViewer.nickName);
                textArea.append("\nFollowers: " + p.myViewer.Hours);
                textArea.append("\n---------------------------");
                p = p.link;
            }
        }


    }//GEN-LAST:event_showButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        BigDecimal id = new BigDecimal(searchTextField.getText());
        if (searchComboBox.getSelectedIndex() == 0) {
            ListDonations p = new ListDonations();
            p = myDonations;
            while ((p.myDonation.idDonations.compareTo(id) != 0) && (p != null)) {
                p = p.link;
            }
            if (p.myDonation.idDonations.compareTo(id) == 0) {
                textArea.setText("The donation was found");
                textArea.append("\n------------------------");
                textArea.append("\nMessage: " + p.myDonation.msg);
                textArea.append("\nMoney: " + p.myDonation.money);
                textArea.append("\n-------------------------");
            } else {
                textArea.setText("The donation doesn´t exist");
            }
        }
        if (searchComboBox.getSelectedIndex() == 1) {
            ListStreamers p = new ListStreamers();
            p = myStreamers;
            while ((p.myStreamer.idStreamer.compareTo(id) != 0) && (p != null)) {
                p = p.link;
            }
            if (p.myStreamer.idStreamer.compareTo(id) == 0) {
                textArea.setText("The streamer was found");
                textArea.append("\n------------------------");
                textArea.append("\nUsername: " + p.myStreamer.userName);
                textArea.append("\nFollowers: " + p.myStreamer.followers);
                textArea.append("\n--------------------------");
            } else {
                textArea.setText("The streamer don´t exist");
            }
        }
        if (searchComboBox.getSelectedIndex() == 2) {
            ListViewers p = new ListViewers();
            p = myViewers;
            while ((p.myViewer.idViewer.compareTo(id) != 0) && (p != null)) {
                p = p.link;
            }
            if (p.myViewer.idViewer.compareTo(id) == 0) {
                textArea.setText("The viewer was found");
                textArea.append("\n--------------------------");
                textArea.append("\nNickname: " + p.myViewer.nickName);
                textArea.append("\nhours: " + p.myViewer.Hours);
                textArea.append("\n--------------------------");
            } else {
                textArea.setText("The viewer don´t exist");
            }
        }


    }//GEN-LAST:event_searchButtonActionPerformed

    private void calcButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcButtonActionPerformed
        if (calcComboBox.getSelectedIndex() == 0) {
            ListDonations min = new ListDonations();
            float minMoney;
            ListDonations max = new ListDonations();
            float maxMoney;

            float promMoney;
            float total = 0;
            int nDonations = 0;

            ListDonations p = new ListDonations();
            p = myDonations;
            minMoney = p.myDonation.money;
            maxMoney = p.myDonation.money;
            min.myDonation = p.myDonation;
            max.myDonation = p.myDonation;
            while ((p != null) && (p.myDonation != null)) {
                if (p.myDonation.money > maxMoney) {
                    maxMoney = p.myDonation.money;
                    max.myDonation = p.myDonation;
                }
                if (p.myDonation.money < minMoney) {
                    minMoney = p.myDonation.money;
                    min.myDonation = p.myDonation;
                }

                total = total + p.myDonation.money;
                nDonations++;
                p = p.link;
            }
            promMoney = total / nDonations;

            textArea.setText("The donation with the maximum money is: ");
            textArea.append("\n--------------------------------------");
            textArea.append("\nId: " + max.myDonation.idDonations);
            textArea.append("\nMessage: " + max.myDonation.msg);
            textArea.append("\nMoney: " + max.myDonation.money);
            textArea.append("\n--------------------------------------");
            textArea.append("\nThe donation with the minimum money is: ");
            textArea.append("\n--------------------------------------");
            textArea.append("\nId: " + min.myDonation.idDonations);
            textArea.append("\nMessage: " + min.myDonation.msg);
            textArea.append("\nMoney: " + min.myDonation.money);
            textArea.append("\n--------------------------------------");
            textArea.append("\nAverage money: " + promMoney);
        }
        if (calcComboBox.getSelectedIndex() == 1) {
            ListStreamers min = new ListStreamers();
            float minFollowers;
            ListStreamers max = new ListStreamers();
            float maxFollowers;

            float promFollowers;
            float total = 0;
            int nStreamers = 0;

            ListStreamers p = new ListStreamers();
            p = myStreamers;
            minFollowers = p.myStreamer.followers;
            maxFollowers = p.myStreamer.followers;
            min.myStreamer = p.myStreamer;
            max.myStreamer = p.myStreamer;
            while ((p != null) && (p.myStreamer != null)) {
                if (p.myStreamer.followers > maxFollowers) {
                    maxFollowers = p.myStreamer.followers;
                    max.myStreamer = p.myStreamer;
                }
                if (p.myStreamer.followers < minFollowers) {
                    minFollowers = p.myStreamer.followers;
                    min.myStreamer = p.myStreamer;
                }

                total = total + p.myStreamer.followers;
                nStreamers++;
                p = p.link;
            }
            promFollowers = total / nStreamers;

            textArea.setText("The streamer with the maximum followers is: ");
            textArea.append("\n--------------------------------------");
            textArea.append("\nId: " + max.myStreamer.idStreamer);
            textArea.append("\nUsername: " + max.myStreamer.userName);
            textArea.append("\nFollowers: " + max.myStreamer.followers);
            textArea.append("\n--------------------------------------");
            textArea.append("\nThe streamer with the maximum followers is: ");
            textArea.append("\n--------------------------------------");
            textArea.append("\nId: " + min.myStreamer.idStreamer);
            textArea.append("\nUsername: " + min.myStreamer.userName);
            textArea.append("\nFollowers: " + min.myStreamer.followers);
            textArea.append("\n--------------------------------------");
            textArea.append("\nAverage followers: " + promFollowers);

        }
        if (calcComboBox.getSelectedIndex() == 2) {
            ListViewers min = new ListViewers();
            float minHours;
            ListViewers max = new ListViewers();
            float maxHours;

            float promHours;
            float total = 0;
            int nViewers = 0;

            ListViewers p = new ListViewers();
            p = myViewers;
            minHours = p.myViewer.Hours;
            maxHours = p.myViewer.Hours;
            min.myViewer = p.myViewer;
            max.myViewer = p.myViewer;
            while ((p != null) && (p.myViewer != null)) {
                if (p.myViewer.Hours > maxHours) {
                    maxHours = p.myViewer.Hours;
                    max.myViewer = p.myViewer;
                }
                if (p.myViewer.Hours < minHours) {
                    minHours = p.myViewer.Hours;
                    min.myViewer = p.myViewer;
                }

                total = total + p.myViewer.Hours;
                nViewers++;
                p = p.link;
            }
            promHours = total / nViewers;

            textArea.setText("The viewer with the maximum hours is: ");
            textArea.append("\n--------------------------------------");
            textArea.append("\nId: " + max.myViewer.idViewer);
            textArea.append("\nNickname: " + max.myViewer.nickName);
            textArea.append("\nHours: " + max.myViewer.Hours);
            textArea.append("\n--------------------------------------");
            textArea.append("\nThe viewer with the minimum hours is: ");
            textArea.append("\n--------------------------------------");
            textArea.append("\nId: " + min.myViewer.idViewer);
            textArea.append("\nNickname: " + min.myViewer.nickName);
            textArea.append("\nHours: " + min.myViewer.Hours);
            textArea.append("\n--------------------------------------");
            textArea.append("\nAverage hours: " + promHours);

        }
    }//GEN-LAST:event_calcButtonActionPerformed

    private void sortButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortButtonActionPerformed
        if (sortComboBox.getSelectedIndex() == 0) {
            ListDonations p = new ListDonations();
            ListDonations q = new ListDonations();
            p = myDonations;
            while ((p.link != null) && (p.link.myDonation != null)) {
                q = myDonations;
                while ((q.link != null) && (q.link.myDonation != null)) {
                    if (q.myDonation.money > q.link.myDonation.money) {
                        ListDonations temp = new ListDonations();
                        temp.myDonation = q.myDonation;
                        q.myDonation = q.link.myDonation;
                        q.link.myDonation = temp.myDonation;
                    }
                    q = q.link;
                }
                p = p.link;
            }
        }
        if (sortComboBox.getSelectedIndex() == 1) {
            ListStreamers p = new ListStreamers();
            ListStreamers q = new ListStreamers();
            p = myStreamers;

            while ((p.link != null) && (p.link.myStreamer != null)) {
                q = myStreamers;
                while ((q.link != null) && (q.link.myStreamer != null)) {
                    if (q.myStreamer.followers > q.link.myStreamer.followers) {
                        ListStreamers temp = new ListStreamers();
                        temp.myStreamer = q.myStreamer;
                        q.myStreamer = q.link.myStreamer;
                        q.link.myStreamer = temp.myStreamer;
                    }
                    q = q.link;
                }
                p = p.link;
            }
        }
        if (sortComboBox.getSelectedIndex() == 2) {
            ListViewers p = new ListViewers();
            ListViewers q = new ListViewers();
            p = myViewers;

            while ((p.link != null) && (p.link.myViewer != null)) {
                q = myViewers;
                while ((q.link != null) && (q.link.myViewer != null)) {
                    if (q.myViewer.Hours > q.link.myViewer.Hours) {
                        ListViewers temp = new ListViewers();
                        temp.myViewer = q.myViewer;
                        q.myViewer = q.link.myViewer;
                        q.link.myViewer = temp.myViewer;
                    }
                    q = q.link;
                }
                p = p.link;
            }
        }
    }//GEN-LAST:event_sortButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        BigDecimal id = new BigDecimal(idAddTextField.getText());
        String name = stringAddTextField.getText();
        float nfloat = Float.parseFloat(floatAddTextField.getText());
        if (addComboBox.getSelectedIndex() == 0) {
            Donations d = new Donations(id, name, nfloat);
            ListDonations p = new ListDonations();
            p = myDonations;

            if (p.myDonation == null) {
                myDonations.myDonation = d;
            } else {
                while (p.link != null) {
                    p = p.link;
                }
                ListDonations q = new ListDonations();
                p.link = q;
                q.myDonation = d;
            }
        }
        if (addComboBox.getSelectedIndex() == 1) {
            Streamer d = new Streamer(id, name, nfloat);
            ListStreamers p = new ListStreamers();
            p = myStreamers;

            if (p.myStreamer == null) {
                myStreamers.myStreamer = d;
            } else {
                while (p.link != null) {
                    p = p.link;
                }
                ListStreamers q = new ListStreamers();
                p.link = q;
                q.myStreamer = d;
            }
        }
        if (addComboBox.getSelectedIndex() == 2) {
            Viewer d = new Viewer(id, name, nfloat);
            ListViewers p = new ListViewers();
            p = myViewers;
            if (p.myViewer == null) {
                myViewers.myViewer = d;
            } else {
                while (p.link != null) {
                    p = p.link;
                }
                ListViewers q = new ListViewers();
                p.link = q;
                q.myViewer = d;
            }
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        as.write(myStreamers);
        av.write(myViewers);
        ad.write(myDonations);
    }//GEN-LAST:event_saveButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame GUI;
    private javax.swing.JButton GUIButton;
    private javax.swing.JButton addButton;
    private javax.swing.JComboBox<String> addComboBox;
    private javax.swing.JButton calcButton;
    private javax.swing.JComboBox<String> calcComboBox;
    private javax.swing.JButton consoleButton;
    private javax.swing.JTextField floatAddTextField;
    private javax.swing.JButton generateButton;
    private javax.swing.JTextField idAddTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JComboBox<String> searchComboBox;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JButton showButton;
    private javax.swing.JComboBox<String> showComboBox;
    private javax.swing.JButton sortButton;
    private javax.swing.JComboBox<String> sortComboBox;
    private javax.swing.JTextField stringAddTextField;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
}
